<a href="https://colab.research.google.com/github/Harish-b19/python/blob/main/13_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
'''NumPy Retail Analytics Assignment
Business Scenario
You are working as a Data Analyst for SmartMart Retail Stores. The company operates five stores in different cities and sells six major product categories.

Management wants to analyze sales performance, expenses, profits, targets, discounts, inventory, and store-level performance using NumPy.

You are provided with two main NumPy arrays:

sales_data — monthly sales revenue generated by each store for different product categories.
cost_data — total cost incurred by each store for the same product categories.'''

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

print("Stores:")
print(stores)

print("\nProduct Categories:")
print(categories)

print("\nSales Data:")
print(sales_data)

print("\nCost Data:")
print(cost_data)

print("==========\n")
k=sales_data.sum(axis=1)
print(k)

print("==========\n")
l=cost_data.sum(axis=1)
print(l)




Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']

Product Categories:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']

Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]

[2270000 2295000 2310000 2820000 1980000]

[1665000 1685000 1710000 2065000 1475000]


Part 2: Basic Array Understanding

In [ ]:
'''Question 1: Array Dimensions
The finance manager wants to confirm how many stores and product categories are present in the data.

Write NumPy code to display:

Number of dimensions in sales_data
Shape of sales_data
Total number of values
Data type of the array
Memory occupied by the array'''

#ndimension
k=sales_data.ndim
print(k)
print("===")
#shape
l=sales_data.shape
print(l)

print("====\n")
m=sales_data.size   #size of array
print(m)

print("====\n")         #type of data
print(type(sales_data))

print("===\n")            #memory occupied
print(sales_data.nbytes)


2
===
(5, 6)
====

30
====

<class 'numpy.ndarray'>
===

240


In [ ]:
'''Question 2: Store and Category Count
Calculate the following:

Total number of stores
Total number of product categories
Total number of store-category combinations'''

c=sales_data.shape[0]  #count rows
print(c)
p=sales_data.shape[1]  #count columns
print(p)
sc=sales_data.size     #combination of rows and columns
print(sc)



5
6
30


In [ ]:
'''Question 3: Sales Data Type Conversion
The reporting application requires sales values in floating-point format.

Convert sales_data into:

float32
float64
Compare the memory used by both arrays.'''

k=sales_data.astype(np.float32) # convert into float32
print(k.dtype) #dtype=datatype.if k means digital data

k2=sales_data.astype(np.float64)
print(k2.dtype)

float32
float64


Part 3: Indexing and Data Extraction

In [ ]:
'''Question 4: Bengaluru Store Analysis
The Bengaluru regional manager wants to review sales for all product categories.

Extract and display the complete sales row for Bengaluru.'''

k=sales_data[0]   #particular row printing
print(k)

[850000 420000 310000 275000 190000 225000]


In [ ]:
'''Question 5: Mumbai Cost Analysis
Extract the total cost incurred by the Mumbai store for all product categories.'''

k=cost_data[3].sum() # particular row sum
print(k)

2065000


In [ ]:
'''Question 6: Electronics Sales Across Stores
The electronics department wants to compare its sales performance across all five stores.

Extract the Electronics sales column from sales_data.'''

e=sales_data[:,0].sum()
print(e)

4290000


In [ ]:
'''Question 7: Clothing Cost Across Stores
Extract the Clothing cost for every store from cost_data.'''

k=cost_data[:,2]
print(k)

[220000 210000 245000 265000 205000]


In [ ]:
'''Question 8: Hyderabad Furniture Performance
Find the following for Hyderabad:

Furniture sales
Furniture cost
Furniture profit'''

k=sales_data[1,3].sum()   #sales of furniture from hyderabad
k2=cost_data[1,3].sum()   #cost of furniture from hyderabad
k3=k-k2                   #profit
print(k,k2,k3)


310000 225000 85000


In [ ]:
'''Question 9: Chennai Category Range
Extract Chennai’s sales for the following categories:

Groceries
Clothing
Furniture
Use array slicing.'''
k=sales_data[2,1:4]
print(k)

[390000 340000 260000]


In [ ]:
'''Question 10: Selected Store Analysis
Extract sales data for:

Bengaluru
Chennai
Pune
Include only:

Electronics
Clothing
Beauty
Use advanced indexing.'''
k=sales_data[0:5:2,0:6:2]  #skip one row using step 2,slicing
print(k)
print("========")
k1=sales_data[np.ix_([0,2,4],[0,2,4])] #select wanted rows,columns manually
print(k1)

[[850000 310000 190000]
 [920000 340000 185000]
 [690000 280000 175000]]
[[850000 310000 190000]
 [920000 340000 185000]
 [690000 280000 175000]]


Part 4: Sales Aggregation

In [ ]:
'''Question 11: Company-Wide Sales
Calculate the total sales revenue generated by all stores and all categories.'''

k=sales_data.sum()  #sum entire rows and columns
print(k)


11675000


In [ ]:
'''Question 12: Store-Wise Sales
Calculate total sales revenue for each store.

Display the result together with the store names.

Expected output format:'''

k=sales_data.sum(axis=1)
for city,total in zip(stores,k):
  print(city,":",total)

Bengaluru : 2270000
Hyderabad : 2295000
Chennai : 2310000
Mumbai : 2820000
Pune : 1980000


In [ ]:
'''
Question 13: Category-Wise Sales
Calculate total sales for each product category across all stores.

Display each category name with its total sales'''

k=sales_data.sum(axis=0)
for store,products in zip(categories,k):
  print(store,":",products)



Electronics : 4290000
Groceries : 2185000
Clothing : 1600000
Furniture : 1415000
Beauty : 1010000
Sports : 1175000


In [ ]:
'''Question 14: Average Sales Per Store
Calculate the average sales generated by each store across all six product categories.'''

k=sales_data.mean(axis=1)

for store,prod in zip(stores,k):
  print(store,":",round(prod,2))


Bengaluru : 378333.33
Hyderabad : 382500.0
Chennai : 385000.0
Mumbai : 470000.0
Pune : 330000.0


In [ ]:
'''Question 15: Average Sales Per Category
Calculate the average sales of each product category across the five stores.'''

k=sales_data.mean(axis=0)
print(k)

[858000. 437000. 320000. 283000. 202000. 235000.]


In [ ]:
'''Question 16: Highest-Selling Store
Identify:

Index of the store with the highest total sales
Name of the store
Total sales generated by that store
Use np.argmax().'''
k=sales_data.sum(axis=1)
k1=k.argmax()
print("total_sales",k)
print("index_value",stores[k1])
print("total sales:",k[k1])


total_sales [2270000 2295000 2310000 2820000 1980000]
index_value Mumbai
total sales: 2820000


In [ ]:
'''Question 17: Lowest-Selling Store
Identify the store with the lowest overall sales.

Use np.argmin().'''

k=sales_data.sum(axis=1)
k1=k.argmin()
print(k1)

4


In [ ]:
'''Question 18: Highest-Selling Category
Find the product category that generated the highest total sales across the company.'''

k=sales_data.sum(axis=0)
k1=k.argmax()
print(k1)
print(k.max())
print(categories[k1])

0
4290000
Electronics


In [ ]:
'''Question 19: Lowest-Selling Category
Find the product category with the lowest total sales across all stores.'''

k=sales_data.sum(axis=0)
k1=k.argmin()           #index
print(categories[k1])  #min product name
print(k1)
print(k.max())# lowest value

Beauty
4


Part 5: Cost Analysis

In [ ]:
'''Question 20: Total Company Cost
Calculate the total cost incurred by SmartMart across all stores and product categories.'''

k=cost_data.sum()
print(k)

8600000


In [ ]:
'''Question 21: Store-Wise Cost
Calculate the total cost incurred by each store.'''
k=cost_data.sum(axis=1)
for store,value in zip(stores,k):
  print(store ,":",value)

Bengaluru : 1665000
Hyderabad : 1685000
Chennai : 1710000
Mumbai : 2065000
Pune : 1475000


In [ ]:
'''Question 22: Category-Wise Cost
Calculate the total cost incurred for each product category across all stores.'''
k=cost_data.sum(axis=0)
for product,value in zip(categories,k):
  print(product,":",value)

Electronics : 3250000
Groceries : 1660000
Clothing : 1145000
Furniture : 1045000
Beauty : 665000
Sports : 835000


In [ ]:
'''Question 23: Most Expensive Store
Identify the store with the highest total operating cost.'''
k=cost_data.sum(axis=1)
k1=k.argmax()
print(k[k1])
print(stores[k1])

2065000
Mumbai


In [ ]:
'''Question 24: Lowest-Cost Store
Identify the store with the lowest total cost.'''
k=cost_data.sum(axis=1)
k1=k.argmin()
print(k[k1])
print(stores[k1])

1475000
Pune


In [ ]:
'''Question 25: Most Expensive Product Category
Determine which product category has the highest total cost across all stores.'''

k=cost_data.sum(axis=0)
k1=k.argmax()
print(k[k1])
print(categories[k1])

3250000
Electronics


Part 6: Profit Analysis Using Two Arrays

In [ ]:
'''Question 26: Profit Matrix
Calculate the profit generated for every store and product category.'''

k=sales_data-cost_data
print(k)



[[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]


In [ ]:
'''Question 27: Store-Wise Profit
Calculate the total profit generated by each store.'''
k=(sales_data-cost_data).sum(axis=1)
print(k)

[605000 610000 600000 755000 505000]


In [ ]:
'''Question 28: Category-Wise Profit
Calculate the total profit generated by each product category.'''
k=(sales_data-cost_data).sum(axis=0)
print(k)

[1040000  525000  455000  370000  345000  340000]


In [ ]:
'''Question 29: Most Profitable Store
Identify the store that generated the highest total profit.

Display:

Store name
Total sales
Total cost
Total profit'''

k=(sales_data-cost_data).sum(axis=1)
k1=k.argmax()
k2=stores[k1]
k3=sales_data.sum(axis=1)[k1]
k4=cost_data.sum(axis=1)[k1]
k5=stores[k1]
print("total_sales: ",k3)
print("total_cost: ",k4)
print("profit store",k5)


total_sales:  2820000
total_cost:  2065000
profit store Mumbai


In [ ]:
'''Question 30: Least Profitable Store
Identify the store that generated the lowest total profit.'''
k=(sales_data-cost_data).sum(axis=1) #total profit store
k1=k.argmin()
print(stores[k1])#least store


Pune


In [ ]:
'''Question 31: Most Profitable Category
Find the category with the highest total profit across all stores.'''
k=(sales_data-cost_data).sum(axis=0)#profit of categories
k1=k.argmax() #index
k2=categories[k1] # finding product category name
print(k2)

Electronics


In [ ]:
'''Question 32: Least Profitable Category
Find the category with the lowest total profit.'''
k=(sales_data-cost_data).sum(axis=0)#profit
k1=k.argmin() #minimum value
k2=categories[k1]
print(k2)

Sports


In [ ]:
'''Question 33: Maximum Individual Profit
Find the highest profit generated by any single store-category combination.

Display:

Profit amount
Store name
Product category
Use np.unravel_index().'''
k=sales_data-cost_data
k1=k.argmax()
s,c=np.unravel_index(k1,k.shape)#get exact require matrix using rows and columns
print("profit: ",k[s,c]) #get profit value based on slicing
print("store: ",stores[s])#store name
print("category: ",categories[c])#category name
print(f"store:{stores[s]},categories:{categories[c]}")

profit:  260000
store:  Mumbai
category:  Electronics
store:Mumbai,categories:Electronics


In [ ]:
'''Question 34: Minimum Individual Profit
Find the smallest profit generated by a store-category combination.

Display the corresponding store and category.'''
k=sales_data-cost_data
k1=k.argmin()
r,c=np.unravel_index(k1,k.shape)
print("min profit: ",k[r,c])
print("store name: ",stores[r])
print("category name: ",categories[c])



min profit:  55000
store name:  Pune
category name:  Furniture


Part 7: Profit Margin Analysis

In [ ]:
'''Question 35: Profit Margin Matrix
Calculate the profit margin percentage for every store-category combination.'''

k=sales_data-cost_data #profit
k1=(k/sales_data)*100  #margin(profit/sales_data)*100
print(np.round(k1,2))

[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]


In [ ]:
'''Question 36: Store-Wise Profit Margin
Calculate the overall profit margin percentage for each store using:'''
k=sales_data.sum(axis=1)-cost_data.sum(axis=1)
k1=(k/sales_data.sum(axis=1))*100
print(np.round(k1,2))

[26.65 26.58 25.97 26.77 25.51]


In [ ]:
'''Question 37: Category-Wise Profit Margin
Calculate the overall profit margin percentage for each product category.'''
k=sales_data.sum(axis=0)-cost_data.sum(axis=0) #profit category-wise
k1=(k/sales_data.sum(axis=0))*100 #convert into percentage
print(np.round(k1,2))

[24.24 24.03 28.44 26.15 34.16 28.94]


In [ ]:
'''Question 38: Best Store by Profit Margin
Identify the store with the highest overall profit margin.'''
k=sales_data.sum(axis=1)-cost_data.sum(axis=1)# category profit
k1=(k/sales_data.sum(axis=1))*100 #convert into percent
k2=k1.argmax() #fingding index
k3=stores[k2] #get name
print(k3)

Mumbai


In [ ]:
'''Question 39: Best Category by Profit Margin
Identify the product category with the highest profit margin.'''
k=sales_data.sum(axis=0)-cost_data.sum(axis=0)
k1=k/sales_data.sum(axis=0)
k2=k1.argmax()
k3=categories[k2]
print(k3)

Beauty


In [ ]:
'''Question 40: Low-Margin Transactions
Management considers a profit margin below 22% to be weak.

Find all store-category combinations where the profit margin is below 22%.

Display:

Store
Category
Sales
Cost
Profit
Profit margin
Use Boolean indexing.'''

k=sales_data-cost_data
k1=(k/sales_data)*100
#k2=k1<22 # percentage <22%
r1,c1=np.where(k1<22)
for r,c in zip(r1,c1):
  print(stores[r],
        categories[c],
        sales_data[r,c],
        cost_data[r,c],
        k[r,c],
        round(k1[r,c],2))


Part 8: Boolean Filtering

In [ ]:
'''Question 41: High Sales Values
Find all sales values greater than ₹5,00,000.'''
k=sales_data>500000
print(sales_data[k])

[ 850000  780000  920000 1050000  510000  690000]


In [ ]:
'''Question 42: Low Sales Values
Find all sales values below ₹2,00,000'''
k=sales_data<200000
print(sales_data[k])

[190000 185000 175000]


In [ ]:
'''Question 43: High Profit Values
Find all store-category combinations where profit is greater than ₹1,50,000.'''
k=sales_data-cost_data
r,c=np.where(k>150000)

for ro,col in zip(r,c):
  print(stores[ro],categories[col],k[ro,col])

Bengaluru Electronics 210000
Hyderabad Electronics 190000
Chennai Electronics 220000
Mumbai Electronics 260000
Pune Electronics 160000


In [ ]:
'''Question 44: Moderate Sales Range
Find sales values between ₹2,50,000 and ₹5,00,000.'''
k=np.logical_and(sales_data>=250000,sales_data<=500000)
print(sales_data[k])

[420000 310000 275000 460000 295000 310000 390000 340000 260000 375000
 345000 250000 290000 405000 280000]


In [ ]:
'''Question 45: Premium Performance
A store-category combination is considered premium when:

Sales are greater than ₹5,00,000
Profit is greater than ₹1,50,000
Find all premium-performing combinations.'''
k=sales_data-cost_data #profit
k1=sales_data #sales
k2=sales_data>500000 #sales>
k3=k>150000 #profit>
k4=np.logical_and(k2,k3)
print(k[k4])

[210000 190000 220000 260000 160000]


In [ ]:
'''Question 46: Underperforming Combinations
A store-category combination is considered underperforming when:

Sales are below ₹2,50,000
Profit margin is below 25%
Find all such combinations.'''
k=sales_data-cost_data #profit
k1=sales_data<250000
k2=(k/sales_data)*100
k3=k2<25
k4=np.logical_and(k1,k3)
print(k[k4])

[55000]


In [ ]:
'''Question 47: Category Performance Classification
Create a new array that classifies every sales value as:

"High" when sales are at least ₹5,00,000
"Medium" when sales are between ₹2,50,000 and ₹4,99,999
"Low" when sales are below ₹2,50,000
Use np.where() or np.select().'''

k=np.select([sales_data>=500000,np.logical_and(sales_data>=250000,sales_data<=499999),sales_data<250000],
              ["High","Medium","low"],
            default="other"
            )
print(k)

[['High' 'Medium' 'Medium' 'Medium' 'low' 'low']
 ['High' 'Medium' 'Medium' 'Medium' 'low' 'low']
 ['High' 'Medium' 'Medium' 'Medium' 'low' 'low']
 ['High' 'High' 'Medium' 'Medium' 'Medium' 'Medium']
 ['High' 'Medium' 'Medium' 'low' 'low' 'low']]


Part 9: Target-Based Analysis
Use the following category-wise monthly sales targets:

In [ ]:
sales_targets = np.array([
    800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])

In [ ]:
'''Question 48: Target Comparison
Compare every store’s category sales against sales_targets.

Use NumPy broadcasting.'''
k=np.where(sales_data>sales_targets)
print(k)

(array([0, 1, 1, 1, 1, 2, 2, 3, 3, 3, 3, 3, 3]), array([0, 1, 3, 4, 5, 0, 2, 0, 1, 2, 3, 4, 5]))


In [ ]:
'''Question 49: Target Achievement Matrix
Create a Boolean array where:

True means the store achieved the category target
False means the store failed to achieve the target'''

k=np.select([sales_data>=sales_targets],
            [True],default=False
             )
print(k)


[[ True False False False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]


In [ ]:
'''Question 50: Target Achievement Count
Calculate the number of categories in which each store achieved its target.'''
k=sales_data>=sales_targets
k1=np.sum(k,axis=1)
print(k1)


[1 4 2 6 0]


In [ ]:
'''Question 51: Best Target-Performing Store
Find the store that achieved the highest number of category targets.'''
k=sales_data>=sales_targets # target
k1=k.sum(axis=1) #store level
k2=k1.argmax()  # got index
print(stores[k2]) #get store name

Mumbai


In [ ]:
'''Question 52: Target Achievement by Category
Calculate how many stores achieved the target for each product category.'''
k=sales_data>=sales_targets
k1=k.sum(axis=0)
print(k1)



[3 2 2 2 2 2]


In [ ]:
'''Question 53: Sales Target Variance
Calculate the difference between actual sales and target sales for every store.

Use: Variance = Actual Sales - Target Sales '''

k=sales_data-sales_targets #difference
print(k)


[[  50000  -30000  -10000  -25000  -10000   -5000]
 [ -20000   10000  -25000   10000   10000   10000]
 [ 120000  -60000   20000  -40000  -15000  -15000]
 [ 250000   60000   55000   45000   50000   60000]
 [-110000  -45000  -40000  -75000  -25000  -25000]]


In [ ]:
'''Question 54: Percentage Above or Below Target
Calculate the percentage variance from the target using:

Percentage Variance =
(Actual Sales - Target Sales) / Target Sales × 100'''
k=(sales_data-sales_targets)/sales_targets*100
print(np.round(k,2))

[[  6.25  -6.67  -3.12  -8.33  -5.    -2.17]
 [ -2.5    2.22  -7.81   3.33   5.     4.35]
 [ 15.   -13.33   6.25 -13.33  -7.5   -6.52]
 [ 31.25  13.33  17.19  15.    25.    26.09]
 [-13.75 -10.   -12.5  -25.   -12.5  -10.87]]


In [ ]:
'''Question 55: Stores Missing Electronics Target
Identify stores that failed to achieve the Electronics sales target.'''
k=np.where(categories=="Electronics")[0][0]
k1=sales_data[:,k]<sales_targets[k]
print(stores[k1])

['Hyderabad' 'Pune']


In [ ]:
'''uestion 56: Stores Achieving All Targets
Check whether any store achieved its target in all six product categories.

Use np.all().'''
k=sales_data>=sales_targets
k1=np.all(k,axis=1)
print(stores[k1])


['Mumbai']


In [ ]:
'''Question 57: Stores Achieving At Least One Target
Identify stores that achieved at least one category target.

Use np.any().'''
k=sales_data>=sales_targets
k1=np.any(k,axis=1)
print(stores[k1])

['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai']


Part 10: Discount Scenario

SmartMart plans to offer category-wise discounts:

In [ ]:
discount_rates = np.array([
    0.10,  # Electronics: 10%
    0.05,  # Groceries: 5%
    0.15,  # Clothing: 15%
    0.12,  # Furniture: 12%
    0.08,  # Beauty: 8%
    0.10   # Sports: 10%
])

In [ ]:
'''Question 58: Discount Amount Matrix
Calculate the discount amount for each store-category combination.

Use broadcasting'''
k=sales_data*discount_rates/100 #discount

print(k)

[[ 850.   210.   465.   330.   152.   225. ]
 [ 780.   230.   442.5  372.   168.   240. ]
 [ 920.   195.   510.   312.   148.   215. ]
 [1050.   255.   562.5  414.   200.   290. ]
 [ 690.   202.5  420.   270.   140.   205. ]]


In [ ]:
'''
Question 59: Sales After Discount
Calculate the net sales value after applying the category-wise discounts.'''
k=sales_data*discount_rates/100
k1=sales_data-k
print(k1)

[[ 849150.   419790.   309535.   274670.   189848.   224775. ]
 [ 779220.   459770.   294557.5  309628.   209832.   239760. ]
 [ 919080.   389805.   339490.   259688.   184852.   214785. ]
 [1048950.   509745.   374437.5  344586.   249800.   289710. ]
 [ 689310.   404797.5  279580.   224730.   174860.   204795. ]]


In [ ]:
'''Question 60: Profit After Discount
Assuming costs remain unchanged, calculate the new profit after the discounts are applied.'''
dis=sales_data*discount_rates/100  # discount
k=sales_data-dis   # new sales
k2=k-cost_data  #profit after
print(k2)

[[209150.  104790.   89535.   69670.   64848.   64775. ]
 [189220.  109770.   84557.5  84628.   69832.   69760. ]
 [219080.   94805.   94490.   64688.   64852.   59785. ]
 [258950.  119745.  109437.5  94586.   84800.   84710. ]
 [159310.   94797.5  74580.   54730.   59860.   59795. ]]


In [ ]:
'''Question 61: Profit Margin After Discount
Calculate the new profit margin after applying discounts.'''

k=sales_data*discount_rates/100 #discount
k1=sales_data-k  #new sales
k2=k1-cost_data #profit
k3=(k2/k1)*100  #margin
print(np.round(k3,1))


[[24.6 25.  28.9 25.4 34.2 28.8]
 [24.3 23.9 28.7 27.3 33.3 29.1]
 [23.8 24.3 27.8 24.9 35.1 27.8]
 [24.7 23.5 29.2 27.4 33.9 29.2]
 [23.1 23.4 26.7 24.4 34.2 29.2]]


In [ ]:
'''Question 62: Loss-Making Transactions
Check whether any store-category combination becomes loss-making after discounts.

Display the affected store and category names.'''

k=sales_data*discount_rates/100 #discount
k1=sales_data-k  # new sales
k2=k1-cost_data  #profit
r,c=np.where(k2<0) # cjecking transections for loss
for i,j in zip(r,c):
  print(stores[i],":",categories[j])


In [ ]:
'''Question 63: Discount Impact
Calculate how much total revenue the company loses because of the proposed discounts.'''

k=sales_data*discount_rates/100 #discount
k1=k.sum()         #adding discount amount
print(k1)

11463.5


In [ ]:
'''Question 64: Store Most Affected by Discounts
Identify the store that loses the highest amount of revenue due to discounts.'''

k=sales_data*discount_rates/100 #discount
k1=k.sum(axis=1)    #total discount per store
k2=k1.argmax()      #calculating index
k3=stores[k2]        # getting store name
print(k3)


Mumbai


Part 11: Tax and Price Adjustment
The government introduces category-wise tax rates:

In [ ]:
tax_rates = np.array([
    0.18,
    0.05,
    0.12,
    0.18,
    0.18,
    0.12
])

In [ ]:
'''Question 65: Tax Collection Matrix
Calculate the tax collected on sales for each store and category.'''
k=sales_data*tax_rates/100 #tax amount
print(k)

[[1530.   210.   372.   495.   342.   270. ]
 [1404.   230.   354.   558.   378.   288. ]
 [1656.   195.   408.   468.   333.   258. ]
 [1890.   255.   450.   621.   450.   348. ]
 [1242.   202.5  336.   405.   315.   246. ]]


In [ ]:
'''Question 66: Sales Including Tax
Calculate the final customer billing value after adding tax.'''

k=sales_data*tax_rates/100
k1=sales_data+k            #tax+sales
print(k1)

[[ 851530.   420210.   310372.   275495.   190342.   225270. ]
 [ 781404.   460230.   295354.   310558.   210378.   240288. ]
 [ 921656.   390195.   340408.   260468.   185333.   215258. ]
 [1051890.   510255.   375450.   345621.   250450.   290348. ]
 [ 691242.   405202.5  280336.   225405.   175315.   205246. ]]


In [ ]:
'''Question 67: Store-Wise Tax Collection
Calculate the total tax collected by each store.'''
k=sales_data*tax_rates/100  #tax amount
k1=k.sum(axis=1)            #store wise
print(k1)


[3219.  3212.  3318.  4014.  2746.5]


In [ ]:
'''Question 68: Category-Wise Tax Collection
Calculate total tax collected for each category.'''
k=sales_data*tax_rates/100
k1=k.sum(axis=0)
print(k1)

[7722.  1092.5 1920.  2547.  1818.  1410. ]


In [ ]:
'''Question 69: Highest Tax-Contributing Store
Identify the store that contributes the highest tax amount.'''
k=sales_data*tax_rates/100
k1=k.sum(axis=1)
k2=k1.argmax()
k3=stores[k2]
print(k3)

Mumbai


Part 12: Array Modification

In [ ]:
'''Question 70: Updated Pune Electronics Sales
The Pune store reports that its Electronics sales were entered incorrectly.

Update Pune Electronics sales from ₹6,90,000 to ₹7,40,000.

Make the change in a copied array without modifying the original array.'''

n=sales_data.copy()
r=np.where(stores=="Pune")[0][0]
c=np.where(categories=="Electronics")[0][0]
n[r,c]=740000
print(n)
print("=====")
print(sales_data)


[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 740000  405000  280000  225000  175000  205000]]
=====
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]


In [ ]:
'''Question 71: Revised Beauty Cost
Due to supplier negotiations, Beauty product costs are reduced by 8% for all stores.

Create an updated cost array.'''
k=cost_data.copy()
k1=cost_data-(cost_data/100)*8
print(k)
print("====")
print(k1)



[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]
====
[[588800. 289800. 202400. 188600. 115000. 147200.]
 [542800. 322000. 193200. 207000. 128800. 156400.]
 [644000. 271400. 225400. 179400. 110400. 142600.]
 [726800. 358800. 243800. 230000. 151800. 188600.]
 [487600. 285200. 188600. 156400. 105800. 133400.]]


In [ ]:
'''Question 72: Furniture Cost Increase
Furniture costs increase by 12% for all stores.

Update only the Furniture column.'''

k=cost_data.copy()
c=np.where(categories=="Furniture")[0][0]
k[:,c]=k[:,c]+(k[:,c]*12/100)
print(k)

[[640000 315000 220000 229600 125000 160000]
 [590000 350000 210000 252000 140000 170000]
 [700000 295000 245000 218400 120000 155000]
 [790000 390000 265000 280000 165000 205000]
 [530000 310000 205000 190400 115000 145000]]


In [ ]:
'''Question 73: Store Closure Simulation
Assume the Pune store is temporarily closed.

Remove Pune’s sales and cost data from the analysis using np.delete().'''
k=sales_data.copy()
k1=cost_data.copy()
r=np.delete(k,np.where(stores=="Pune"),axis=0)
r1=np.delete(k1,np.where(stores=="Pune"),axis=0)
print(r)
print(r1)


[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]]
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]]


Question 74: Adding a New Store
A new Delhi store is opened with the following data:

In [ ]:
delhi_sales = np.array([
    880000, 475000, 330000, 290000, 215000, 250000
])

delhi_cost = np.array([
    665000, 360000, 235000, 215000, 145000, 180000
])

k=np.vstack((sales_data,delhi_sales))
k1=np.vstack((cost_data,delhi_cost))
stores=np.append(stores,"Delhi")
stores=np.unique(stores,axis=0)
print(stores)



['Bengaluru' 'Chennai' 'Delhi' 'Hyderabad' 'Mumbai' 'Pune']


Question 75: Adding a New Product Category
SmartMart starts selling Home Appliances.

In [ ]:
home_appliance_sales = np.array([
    360000,
    325000,
    390000,
    420000,
    295000
])

home_appliance_cost = np.array([
    265000,
    240000,
    285000,
    305000,
    225000
])
k=sales_data
k1=cost_data
categories=np.hstack((categories,home_appliance_sales.reshape(-1,1)))
categories=np.hstack((categories,home_appliance_cost.reshape(-1,1)))
categories=np.unique(categories,axis=1)
print(categories)

[[125000 160000 205000 220000 265000 315000 360000 640000]
 [140000 170000 225000 210000 240000 350000 325000 590000]
 [120000 155000 195000 245000 285000 295000 390000 700000]
 [165000 205000 250000 265000 305000 390000 420000 790000]
 [115000 145000 170000 205000 225000 310000 295000 530000]]


Part 13: Sorting and Ranking

In [ ]:
'''Question 76: Sort Stores by Sales
Sort stores in ascending order based on total sales.

Display store names and sales totals.'''

k=sales_data.sum(axis=1)
k1=np.argsort(k)
for i in k1:
  print(stores[i],":",k[i])

Mumbai : 1980000
Bengaluru : 2270000
Chennai : 2295000
Delhi : 2310000
Hyderabad : 2820000


In [ ]:
'''Question 77: Rank Stores by Profit
Rank stores from highest to lowest total profit.

Use np.argsort().'''
k=sales_data.sum(axis=1)-cost_data.sum(axis=1) #profit
k1=np.argsort(k)[::-1] #descending order
print(k[k1])


[755000 610000 605000 600000 505000]


In [ ]:
'''Question 78: Sort Categories by Revenue
Sort product categories from highest to lowest total revenue.'''
k=sales_data.sum(axis=0)
k1=np.argsort(k)[::-1]
print(k[k1])

[4290000 2185000 1600000 1415000 1175000 1010000]


In [ ]:
'''Question 79: Top Three Store-Category Sales
Find the three highest individual sales values in the complete sales matrix.

Display their:

Sales value
Store name
Category name'''

k=sales_data.flatten() #converts matrix into 1d array
k1=np.argsort(k)[-3:][::-1]
r,c=np.unravel_index(k1,sales_data.shape)
for i,j in zip(r,c):
  print(sales_data[i,j],":",stores[i],":",categories[j])



1050000 : Mumbai : Electronics
920000 : Chennai : Electronics
850000 : Bengaluru : Electronics


In [ ]:
'''Question 80: Bottom Three Profits
Find the three lowest profit values in the profit matrix.'''
k=sales_data-cost_data
k1=k.flatten()
k2=np.argsort(k1)[:3]
print(k1[k2])
# r,c=np.unravel_index(k1,k.shape)
# for i,j in zip(r,c):
#   print

[55000 60000 60000]


Part 14: Statistical Analysis

In [ ]:
'''Question 81: Sales Statistics
Calculate the following for the complete sales array:

Minimum
Maximum
Mean
Median
Standard deviation
Variance
25th percentile
50th percentile
75th percentile'''

k=sales_data.min()
k1=sales_data.max()
k2=sales_data.mean()
k3=np.median(sales_data)
k4=np.std(sales_data)
k5=np.var(sales_data)
k6=np.percentile(sales_data,25)
k7=np.percentile(sales_data,50)
k8=np.percentile(sales_data,75)

print("minimum: ",k)
print("maximum: ",k1)
print("mean: ",round(k2,2))
print("median: ",k3)
print("Standard deviation: ",round(k4,2))
print("varience: ",round(k5,2))
print("25%: ",k6)
print("50%: ",k7)
print("75%: ",k8)


minimum:  175000
maximum:  1050000
mean:  389166.67
median:  302500.0
Standard deviation:  230322.54
varience:  53048472222.22
25%:  228750.0
50%:  302500.0
75%:  416250.0


In [ ]:
'''Question 82: Store-Wise Standard Deviation
Calculate the sales standard deviation for every store.

Use this value to determine which store has the most variation between product categories.'''
k=np.std(sales_data,axis=1)
k1=k.argmax()
print(k[k1])
print(stores[k1])

271860.871280391
Mumbai


In [ ]:
'''Question 83: Category-Wise Standard Deviation
Determine which product category has the highest variation in sales across stores'''

k=np.std(sales_data,axis=0)
k1=k.argmax()
print(k[k1])
print(categories[k1])

122539.78945632312
Electronics


In [ ]:
'''Question 84: Sales Above Company Average
Calculate the company-wide average sales value.

Count how many store-category sales values are above this average.'''
k=sales_data.mean()
k1=np.sum(sales_data>k)
print(k)
print(k1)

389166.6666666667
10


In [ ]:
'''Question 85: Outlier Detection
Treat any sales value greater than:

Mean + 1.5 × Standard Deviation
as a high-value outlier.

Identify all such sales values.'''
k=sales_data.mean()+1.5*np.std(sales_data)
k1=sales_data[sales_data>k]
print(k1)

[ 850000  780000  920000 1050000]


Part 15: Reshaping and Transformation

In [ ]:
'''Question 86: Flatten Sales Data
Convert the two-dimensional sales array into a one-dimensional array using:

flatten()
ravel()
Explain the difference between the two methods.'''

k=sales_data.flatten()
k1=sales_data.ravel()
print(k)
print(k1)

#flatten=it wont affect original data
#ravel =it changes the original data

[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]
[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]


In [ ]:
'''Question 87: Reshape Sales Data
Reshape the 5 × 6 sales array into:

3 × 10
10 × 3
2 × 15
15 × 2
Verify that no data is lost.'''
k=sales_data.reshape(3,10)
k1=sales_data.reshape(10,3)
k2=sales_data.reshape(2,15)
k3=sales_data.reshape(15,2)
print(k)
print(k1)
print(k2)
print(k3)

[[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000]
 [ 210000  240000  920000  390000  340000  260000  185000  215000 1050000
   510000]
 [ 375000  345000  250000  290000  690000  405000  280000  225000  175000
   205000]]
[[ 850000  420000  310000]
 [ 275000  190000  225000]
 [ 780000  460000  295000]
 [ 310000  210000  240000]
 [ 920000  390000  340000]
 [ 260000  185000  215000]
 [1050000  510000  375000]
 [ 345000  250000  290000]
 [ 690000  405000  280000]
 [ 225000  175000  205000]]
[[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000  210000  240000  920000  390000  340000]
 [ 260000  185000  215000 1050000  510000  375000  345000  250000  290000
   690000  405000  280000  225000  175000  205000]]
[[ 850000  420000]
 [ 310000  275000]
 [ 190000  225000]
 [ 780000  460000]
 [ 295000  310000]
 [ 210000  240000]
 [ 920000  390000]
 [ 340000  260000]
 [ 185000  215000]
 [1050000  510000]
 [ 375000  345000]
 [ 250000  29

In [ ]:
'''Question 88: Transpose Sales Data
Transpose the sales array so that:

Rows represent product categories
Columns represent stores'''
k=sales_data.T
print(k)

[[ 850000  780000  920000 1050000  690000]
 [ 420000  460000  390000  510000  405000]
 [ 310000  295000  340000  375000  280000]
 [ 275000  310000  260000  345000  225000]
 [ 190000  210000  185000  250000  175000]
 [ 225000  240000  215000  290000  205000]]


In [ ]:
'''Question 89: Combined Sales and Cost Array
Stack sales_data and cost_data vertically.

Display the resulting shape.'''
k=np.vstack((sales_data,cost_data))
print(k)

[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 640000  315000  220000  205000  125000  160000]
 [ 590000  350000  210000  225000  140000  170000]
 [ 700000  295000  245000  195000  120000  155000]
 [ 790000  390000  265000  250000  165000  205000]
 [ 530000  310000  205000  170000  115000  145000]]


In [ ]:
'''Question 90: Store-Level Combined Data
Create a three-dimensional array where:

First layer contains sales data
Second layer contains cost data
Use np.stack().

Display the shape of the new array.'''
k=np.stack((sales_data,cost_data))
k1=k.shape
print(k1)

(2, 5, 6)


Part 16: Missing Data Scenario

The company discovers that some sales values were not recorded

In [ ]:


sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])

In [ ]:
'''Question 91: Missing Value Detection
Find:

Total number of missing values
Location of missing values
Stores and categories containing missing values
'''
k=np.isnan(sales_data)
k1=np.sum(k)
r,c= np.where(k)
for i,j in zip(r,c):
  print(stores[i],":",categories[j])
print(k1)

0


In [ ]:
'''Question 92: Replace Missing Values with Zero
Replace all missing sales values with zero.'''
k=sales_data[np.isnan(sales_data)]=0
print(k)

0


In [ ]:
'''Question 93: Replace with Company Average
Replace missing values with the overall average of available sales values.

Use np.nanmean().'''
k=sales_data.copy()
k1=np.nanmean(k)
k2=sales_data[np.isnan(sales_data)]=k1
print(k2)

389166.6666666667
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]


In [ ]:
'''Question 94: Replace with Category Average
Replace each missing value with the average sales value of its respective product category.'''
k=sales_data.copy()
k1=np.nanmean(k,axis=0)
for j in range (k.shape[1]):
  k[np.isnan(k[:,j]),j]=k1[j]
print(k)



[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]


In [ ]:
'''Question 95: Missing Value Impact
Compare total sales before and after replacing missing values with zero.'''

k=np.nansum(sales_data) #before replacing missing values
k1=np.nan_to_num(sales_data,nan=0)
k2=k1.sum()#after replacing
print("before missing",k)
print("after missing",k2)
print("difference",k-k2)


before missing 11675000
after missing 11675000
difference 0


Part 17: Conditional Business Decisions

In [ ]:
'''Question 96: Store Performance Labels
Classify each store based on total sales:

"Excellent": Total sales above ₹28,00,000
"Good": Total sales between ₹24,00,000 and ₹28,00,000
"Needs Improvement": Total sales below ₹24,00,000
Use np.select()'''

k1=sales_data.sum()
k=np.select([k1>2800000,np.logical_and(k1>=2400000,k1<=2800000),k1<2400000],
            ["Excellent","Good","Needs_Improvement"],default="unknown")
print(k)


Excellent


In [ ]:
'''Question 97: Profitability Classification
Classify each store-category combination as:

"Highly Profitable": Profit above ₹2,00,000
"Profitable": Profit between ₹1,00,000 and ₹2,00,000
"Low Profit": Profit below ₹1,00,000
"Loss": Profit below zero'''
k=sales_data-cost_data
k1=np.select([k>200000,np.logical_and(k>=100000,k<=200000),np.logical_and(k>=0,k<100000),k<0],
             ["Highly profitable","profitable","low profit","loss"],default="unknown")
print(k1)

[['Highly profitable' 'profitable' 'low profit' 'low profit' 'low profit'
  'low profit']
 ['profitable' 'profitable' 'low profit' 'low profit' 'low profit'
  'low profit']
 ['Highly profitable' 'low profit' 'low profit' 'low profit' 'low profit'
  'low profit']
 ['Highly profitable' 'profitable' 'profitable' 'low profit' 'low profit'
  'low profit']
 ['profitable' 'low profit' 'low profit' 'low profit' 'low profit'
  'low profit']]


In [ ]:
'''Question 98: Expansion Recommendation
A store is eligible for expansion when:

Total sales are above ₹25,00,000
Total profit is above ₹7,00,000
Overall profit margin is above 25%
Identify eligible stores'''
t=sales_data.sum(axis=1) #total
t1=(sales_data-cost_data).sum(axis=1)#profit
t2=(t1/t)*100 #margin

k=np.logical_and(np.logical_and(t>2500000,t1>700000),t2>25)

t3=np.select([k],["k"],default="unknown")
print(t3)

['unknown' 'unknown' 'unknown' 'k' 'unknown']


In [ ]:
'''Question 99: Category Promotion Recommendation
A product category should receive additional promotion when:

Average sales are below ₹3,00,000
Profit margin is above 25%
Identify the categories that satisfy these conditions.'''
k=sales_data.mean(axis=0)
k1=(sales_data-cost_data).sum(axis=0)
k2=(k1/sales_data.sum(axis=0))*100
t1=np.logical_and(k<300000,k2>25)
print(t1)
print(categories[t1])

[False False False  True  True  True]
['Furniture' 'Beauty' 'Sports']


In [ ]:
'''Question 100: Cost Optimization Recommendation
Find store-category combinations where:

Cost is greater than ₹2,50,000
Profit margin is below 25%
These combinations should be reviewed for cost optimization.
'''
t=cost_data
t1=sales_data-cost_data
t2=(t1/sales_data)*100
t3=np.logical_and(t>250000,t2<25)
r,c=np.where(t3)
for i,j in zip(r,c):
  print(stores[i],":",categories[j])
print(t3)

Bengaluru : Electronics
Hyderabad : Electronics
Hyderabad : Groceries
Chennai : Electronics
Chennai : Groceries
Mumbai : Electronics
Mumbai : Groceries
Pune : Electronics
Pune : Groceries
[[ True False False False False False]
 [ True  True False False False False]
 [ True  True False False False False]
 [ True  True False False False False]
 [ True  True False False False False]]


Part 18: Inventory Scenario
Use the following inventory arrays:

In [ ]:
opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])

In [ ]:
'''Question 101: Closing Stock
Calculate closing stock using:'''

k=opening_stock-units_sold
print(k)

[[25 70 60 25 60 40]
 [25 80 50 25 60 45]
 [25 70 50 25 60 40]
 [25 80 55 30 65 45]
 [25 70 55 20 55 40]]


In [ ]:
'''Question 102: Low-Stock Identification
Identify store-category combinations where closing stock is below 30 units.'''

k=opening_stock-units_sold
r,c=np.where(k<30)
for i,j in zip(r,c):
  print(stores[i],categories[j])

Bengaluru Electronics
Bengaluru Furniture
Hyderabad Electronics
Hyderabad Furniture
Chennai Electronics
Chennai Furniture
Mumbai Electronics
Pune Electronics
Pune Furniture


In [ ]:
'''Question 103: Stock Availability Percentage
Calculate the percentage of opening stock that remains unsold.'''

k=opening_stock-units_sold #closing stock
k1=opening_stock-k/opening_stock*100 #percentage
k2=(k/opening_stock)*100
k3=np.round(k2,2)
print(k3)


[[20.83 15.56 20.   27.78 24.   22.22]
 [22.73 16.   17.86 25.   22.22 22.5 ]
 [19.23 16.67 15.62 29.41 25.   23.53]
 [16.67 14.55 15.71 25.   21.67 20.45]
 [25.   17.5  21.15 26.67 25.   25.  ]]


In [ ]:
'''Question 104: Fast-Moving Products
A product is considered fast-moving when more than 80% of its opening stock has been sold.

Identify fast-moving store-category combinations.'''

k=(units_sold/opening_stock)*100
r,c=np.where(k>80)
for i,j in zip(r,c):
  print(stores[i],":",categories[j])

Bengaluru : Groceries
Hyderabad : Groceries
Hyderabad : Clothing
Chennai : Electronics
Chennai : Groceries
Chennai : Clothing
Mumbai : Electronics
Mumbai : Groceries
Mumbai : Clothing
Pune : Groceries


In [ ]:
'''Question 105: Category-Wise Units Sold
Calculate the total units sold for each product category.'''
k=units_sold.sum(axis=0)
print(k)

[ 485 1950 1240  345  980  720]


In [ ]:
'''Question 106: Store-Wise Units Sold
Calculate total units sold by each store.'''
k=units_sold.sum(axis=1)
print(k)

[1110 1175 1095 1390  950]


In [ ]:
'''Question 107: Best Store by Unit Sales
Identify the store that sold the highest total number of units.'''
k=units_sold.sum(axis=1)
k1=k.argmax()
print(stores[k1])

Mumbai


In [ ]:
'''Question 108: Reorder Requirement
A store should reorder a category when closing stock is below 25 units.

Create a Boolean reorder matrix.'''
k=(opening_stock-units_sold)
r,c=np.where(k<25)
for i,j in zip(r,c):
  print(stores[i],":",categories[j])

Pune : Furniture


In [ ]:
'''Question 109: Reorder Quantity
Assume each category must maintain 100 units after reordering.

Calculate reorder quantities only for combinations where closing stock is below 25.

For all other combinations, return zero'''

k=opening_stock-units_sold #closing stock
k1=100-k #record quantity
k2=np.where(k<25,100-k,0)#records<25
print(k2)



[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0 80  0  0]]


Part 19: Advanced NumPy Questions

In [ ]:
'''Question 110: Cumulative Store Sales
Calculate cumulative category sales for each store using np.cumsum().'''
k=np.cumsum(sales_data,axis=1)
print(k)

[[ 850000 1270000 1580000 1855000 2045000 2270000]
 [ 780000 1240000 1535000 1845000 2055000 2295000]
 [ 920000 1310000 1650000 1910000 2095000 2310000]
 [1050000 1560000 1935000 2280000 2530000 2820000]
 [ 690000 1095000 1375000 1600000 1775000 1980000]]


In [ ]:
'''Question 111: Cumulative Company Sales
Flatten the sales array and calculate cumulative company sales.'''
k=sales_data.flatten()
k1=np.cumsum(k)
print(k1)

[  850000  1270000  1580000  1855000  2045000  2270000  3050000  3510000
  3805000  4115000  4325000  4565000  5485000  5875000  6215000  6475000
  6660000  6875000  7925000  8435000  8810000  9155000  9405000  9695000
 10385000 10790000 11070000 11295000 11470000 11675000]


In [ ]:
'''Question 112: Sales Difference Between Categories
Calculate the difference between consecutive category sales for each store using np.diff().'''

k=np.diff(sales_data,axis=1)
print(k)

[[-430000 -110000  -35000  -85000   35000]
 [-320000 -165000   15000 -100000   30000]
 [-530000  -50000  -80000  -75000   30000]
 [-540000 -135000  -30000  -95000   40000]
 [-285000 -125000  -55000  -50000   30000]]


In [ ]:
'''Question 113: Unique Sales Values
Find all unique sales values in sales_data.

Also count the frequency of each value.'''
r,c=np.unique(sales_data,return_counts=True)
print("unique value",r)
print("frequency",c)

unique value [ 175000  185000  190000  205000  210000  215000  225000  240000  250000
  260000  275000  280000  290000  295000  310000  340000  345000  375000
  390000  405000  420000  460000  510000  690000  780000  850000  920000
 1050000]
frequency [1 1 1 1 1 1 2 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [ ]:
'''Question 114: Search for Specific Sales
Check whether the value ₹4,20,000 exists in the sales array.

Return its location.'''
r,c=np.where(sales_data == 420000)
for i,j in zip(r,c):
  print(stores[i],":",categories[j])

Bengaluru : Groceries


In [ ]:
'''Question 115: Compare Sales and Cost
Create a Boolean array showing whether sales are greater than cost for every combination.

Verify whether all combinations are profitable using np.all().'''
k1=sales_data>cost_data
print(k1)
k=np.all(k1)
print(k)

[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]
True


In [ ]:
'''Question 116: Clip Profit Values
For reporting purposes, management wants profit values limited to:

Minimum: ₹75,000
Maximum: ₹2,50,000
Use np.clip() to create a reporting profit array.'''
k1=sales_data-cost_data
k=np.clip(k1,75000,250000)
print(k)

[[210000 105000  90000  75000  75000  75000]
 [190000 110000  85000  85000  75000  75000]
 [220000  95000  95000  75000  75000  75000]
 [250000 120000 110000  95000  85000  85000]
 [160000  95000  75000  75000  75000  75000]]


In [ ]:
'''Question 117: Normalize Sales Data
Normalize all sales values using min-max normalization:

Normalized Sales =
(Sales - Minimum Sales) / (Maximum Sales - Minimum Sales)'''
k=sales_data-np.min(sales_data)
k1=np.max(sales_data)-np.min(sales_data)
k2=k/k1
k3=np.round(k2,2)
print(k3)

[[0.77 0.28 0.15 0.11 0.02 0.06]
 [0.69 0.33 0.14 0.15 0.04 0.07]
 [0.85 0.25 0.19 0.1  0.01 0.05]
 [1.   0.38 0.23 0.19 0.09 0.13]
 [0.59 0.26 0.12 0.06 0.   0.03]]


In [ ]:
'''Question 118: Standardize Sales Data
Standardize sales using:

Standardized Sales =
(Sales - Mean Sales) / Standard Deviation'''
k=sales_data-sales_data.mean()
k1=np.std(sales_data)
k2=k/k1
print(k2)

[[ 2.00081735  0.13387024 -0.34372088 -0.49568169 -0.86472938 -0.71276857]
 [ 1.69689573  0.30753974 -0.40884695 -0.34372088 -0.77789463 -0.64764251]
 [ 2.30473897  0.00361811 -0.21346876 -0.56080776 -0.88643807 -0.75618594]
 [ 2.86916484  0.52462661 -0.06150795 -0.19176007 -0.60422513 -0.43055563]
 [ 1.30613936  0.06874418 -0.47397301 -0.71276857 -0.92985544 -0.79960332]]


In [ ]:
'''Question 119: Round Values
Convert profit margin values into:

Two decimal places
Nearest whole number
Floor values
Ceiling values'''

k=sales_data-cost_data
k1=(k/sales_data)*100
k2=np.round(k1,2)
k3=np.round(k1)
k4=np.floor(k1)
k5=np.ceil(k1)
print(k2)
print(k3)
print(k4)
print(k5)

[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]
[[25. 25. 29. 25. 34. 29.]
 [24. 24. 29. 27. 33. 29.]
 [24. 24. 28. 25. 35. 28.]
 [25. 24. 29. 28. 34. 29.]
 [23. 23. 27. 24. 34. 29.]]
[[24. 25. 29. 25. 34. 28.]
 [24. 23. 28. 27. 33. 29.]
 [23. 24. 27. 25. 35. 27.]
 [24. 23. 29. 27. 34. 29.]
 [23. 23. 26. 24. 34. 29.]]
[[25. 25. 30. 26. 35. 29.]
 [25. 24. 29. 28. 34. 30.]
 [24. 25. 28. 25. 36. 28.]
 [25. 24. 30. 28. 34. 30.]
 [24. 24. 27. 25. 35. 30.]]


In [ ]:
'''Question 120: Save and Load Data
Save the following arrays as NumPy binary files:

sales_data.npy
cost_data.npy
profit_data.npy
Load them back and verify that the loaded arrays are equal to the original arrays'''

profit=sales_data-cost_data
np.save("sales_data.npy",sales_data)
np.save("cost_data.npy",cost_data)
np.save("profit_data.npy",profit)

Part 20: Final Retail Analytics Project
Prepare a complete NumPy-based retail performance report.

Your report must contain the following information:

Company Summary
Total company sales
Total company cost
Total company profit
Overall company profit margin
Average transaction value
Highest individual sales value
Lowest individual sales value
Store Summary
For every store, display:

Total sales
Total cost
Total profit
Profit margin
Number of category targets achieved
Total units sold
Expansion eligibility
Category Summary
For every category, display:

Total sales
Total cost
Total profit
Profit margin
Average sales
Number of stores achieving the target
Total units sold
Management Recommendations
Based on the analysis, identify:

Best-performing store
Lowest-performing store
Most profitable category
Lowest-profit category
Store recommended for expansion
Category requiring additional marketing
Store-category combinations needing cost optimization
Store-category combinations requiring inventory reorder
Expected Final Output Format
SMARTMART RETAIL PERFORMANCE REPORT
===================================

COMPANY SUMMARY
---------------
Total Sales:
Total Cost:
Total Profit:
Overall Profit Margin:

BEST-PERFORMING STORE
---------------------
Store:
Sales:
Cost:
Profit:
Profit Margin:

MOST PROFITABLE CATEGORY
------------------------
Category:
Sales:
Cost:
Profit:
Profit Margin:

EXPANSION RECOMMENDATIONS
-------------------------
Eligible Stores:

COST OPTIMIZATION
-----------------
Store:
Category:
Cost:
Profit Margin:

INVENTORY REORDER
-----------------
Store:
Category:
Closing Stock:
Reorder Quantity:

In [ ]:
#company summary
import numpy as np
print("company summary\n")
k=sales_data.sum() #total sales
k1=cost_data.sum() #total costs
k2=k-k1 #total profit
k3=(k2/k)*100    # margin
k4=sales_data.mean() #avg transection value
k5=sales_data
k6=k5.max()       #highest value
k7=k5.min()       #minimum value
print("total sales: ",k)
print("\n")
print("total costs: ",k1)
print("\n")
print("total profit: ",k2)
print("\n")
print("margin: ",k3)
print("\n")
print("avg transection: ",k4)
print("highest sales: ",k6)
print("\n")
print("minimum sales: ",k7)
print("\n")

print("Best store performance")
x=sales_data.sum(axis=1)#store sales
x1=cost_data.sum(axis=1)#cost of stores
x2=(sales_data-cost_data).sum(axis=1)#profit()
x4=sales_data.sum(axis=1) #total categories
x3=(x2/x)*100 #margin

ta=1500000
x5=((sales_data)>=ta).sum(axis=1)  #target achieved
x6=units_sold.sum(axis=1)#total units sold
x7=np.logical_and(
    np.logical_and(x>2500000,x2>700000),x3>25) #expansion eligibility
x8=stores[x7]

print("total sales: ",x)
print("\n")
print("total cost: ",x1)
print("\n")
print("total profit: ",x2)
print("\n")
print("profit margin: ",x3)
print("\n")
print("categories achived: ",x5)
print("\n")
print("total units sold: ",x6)
print("\n")
print("expansion eligibility: ",x8)
print("\n")

print("most profit category summary")
print("\n")

t=sales_data.sum(axis=0) #total sales
t1=cost_data.sum(axis=0) #total cost
t2=(sales_data-cost_data).sum(axis=0)#profit
t3=(t2/t)*100 #margin
t4=sales_data.mean(axis=0)#average sales
t5=500000
t6=((sales_data)>=t5).sum(axis=0) # targets
t7=units_sold.sum(axis=0)
print("total sales: ",t)
print("\n")
print("total cost: ",t1)
print("\n")
print("total profit: ",t2)
print("\n")
print("margin: ",t3)
print("\n")
print("average sales: ",t4)
print("\n")
print("target achieved: ",t6)
print("\n")
print("units sold: ",t7)
print("\n")

print("management recommendations")
a=(sales_data-cost_data).sum(axis=1)
a1=a.argmax()
a2=stores[a1]  #best performing store
a3=a2.argmin()
a4=stores[a3] # lowest performance store
a5=(sales_data-cost_data).sum(axis=0)
a6=a5.argmax()
a7=categories[a6]#best profitable categories
a8=stores[a1] # store recommended
a9=sales_data.mean(axis=0) #average sales
a10=(sales_data-cost_data).sum(axis=0) #profit
a11=(a10/sales_data.sum(axis=0) )*100 #profit margin
a12=a9.mean()# benchmark sales limit
a13=a11.mean() #margin limit
a14=np.logical_and(a9<12,a11>a13)
a15=categories[a14] #additional marketing
a16=cost_data.mean()#cost limit
a17=np.logical_and(cost_data>a16,a11<13) #cost optimization
a18=opening_stock-units_sold
a19=a18<25
r,c=np.where(a19)
print(" inventory record ")
for i,j in zip(r,c):
  print(stores[i],":",categories[j])
print("\n")
print("best store: ",a2)
print("\n")
print("lowest store: ",a3)
print("\n")
print("best category: ",a7)
print("\n")
print("store recommend: ",a8)
print("\n")
print("average sales: ",a2)
print("\n")
print("additional marketing: ",a15)
print("\n")
print("cost optimization: ",a17)
print("\n")










company summary

total sales:  11675000


total costs:  8600000


total profit:  3075000


margin:  26.33832976445396


avg transection:  389166.6666666667
highest sales:  1050000


minimum sales:  175000


Best store performance
total sales:  [2270000 2295000 2310000 2820000 1980000]


total cost:  [1665000 1685000 1710000 2065000 1475000]


total profit:  [605000 610000 600000 755000 505000]


profit margin:  [26.65198238 26.5795207  25.97402597 26.77304965 25.50505051]


categories achived:  [0 0 0 0 0]


total units sold:  [1110 1175 1095 1390  950]


expansion eligibility:  ['Mumbai']


most profit category summary


total sales:  [4290000 2185000 1600000 1415000 1010000 1175000]


total cost:  [3250000 1660000 1145000 1045000  665000  835000]


total profit:  [1040000  525000  455000  370000  345000  340000]


margin:  [24.24242424 24.02745995 28.4375     26.14840989 34.15841584 28.93617021]


average sales:  [858000. 437000. 320000. 283000. 202000. 235000.]


target achieved:  [